# provider0 underlay for AWS Direct Connect via Aviatrix Edge MVE
#
# Deploys:
#   1. Aviatrix Megaport access account (aviatrix_account, cloud_type 1048576)
#   2. Aviatrix Edge gateway (aviatrix_edge_megaport) — generates ZTP/cloud-init file
#   3. Aviatrix Edge MVE on Megaport (megaport_mve) — bootstrapped via ZTP
#   4. VXC from MVE to AWS DX partner port (us-east-1, AWSHC)
#   5. Accepts the Hosted Private VIF in the customer AWS account
#
# Prerequisites (from root module):
#   - aws_dx_gateway already exists (var.aws_dx_gateway_id)
#   - VGW already associated with that DX Gateway
#
# To replace with another underlay provider: delete this directory and create
# underlay-<provider>/ with the same var.aws_dx_gateway_id input.

# --- Aviatrix Megaport access account ---
# cloud_type 1048576 = Edge Megaport. No API credentials stored here —
# the ZTP file carries all bootstrapping data.

resource "aviatrix_account" "megaport" {
  account_name = var.aviatrix_account_name
  cloud_type   = 1048576
}

# --- Discover provider0 location ---

data "megaport_location" "this" {
  name = var.provider0_location
}

# --- AWS DX partner port at the same location ---

data "megaport_partner" "aws_dx" {
  connect_type = "AWSHC"
  company_name = "AWS"
  product_name = "US East (N. Virginia) (us-east-1)"
  location_id  = data.megaport_location.this.id
}

# --- Megaport Internet partner port at the same location ---

data "megaport_partner" "internet" {
  connect_type = "TRANSIT"
  location_id  = data.megaport_location.this.id
}

# --- Aviatrix Edge gateway ---
# Registers the gateway in the Controller and writes the ZTP cloud-init file to
# ztp_file_download_path. megaport_mve reads that file via cloud_init.
# ZTP file name: {gw_name}-{site_id}-cloud-init.txt

resource "aviatrix_edge_megaport" "this" {
  account_name           = aviatrix_account.megaport.account_name
  gw_name                = var.aviatrix_edge_gw_name
  site_id                = var.aviatrix_site_id
  ztp_file_download_path = path.module

  interfaces {
    logical_ifname = "wan0"
    ip_address     = var.wan_ip
    gateway_ip     = var.wan_gateway_ip
    wan_public_ip  = var.wan_public_ip
  }

  interfaces {
    logical_ifname = "lan0"
    ip_address     = "192.168.50.10/24"
    gateway_ip     = "192.168.50.1"
  }

  interfaces {
    logical_ifname = "mgmt0"
    enable_dhcp    = true
  }
}

# --- Aviatrix Secure Edge MVE ---
# Bootstrapped via the ZTP cloud-init file generated by aviatrix_edge_megaport.
# ZTP file is written during apply of aviatrix_edge_megaport above.

resource "megaport_mve" "aviatrix_edge" {
  product_name         = var.mve_name
  location_id          = data.megaport_location.this.id
  contract_term_months = var.port_term

  vendor_config = {
    vendor       = "aviatrix"
    image_id     = 177 # Aviatrix Secure Edge g4-202605062026
    product_size = var.mve_size
    cloud_init   = try(base64encode(file("${path.module}/${var.aviatrix_edge_gw_name}-${var.aviatrix_site_id}-cloud-init.txt")), "")
  }

  vnics = [
    { description = "WAN" },
    { description = "LAN" },
    { description = "MGMT" },
  ]

  depends_on = [aviatrix_edge_megaport.this]
}

# --- VXC from Aviatrix Edge MVE to AWS DX (Hosted Connection) ---

resource "megaport_vxc" "aws_dx" {
  product_name         = var.vxc_name
  rate_limit           = var.vxc_bandwidth
  contract_term_months = var.port_term

  a_end = {
    requested_product_uid = megaport_mve.aviatrix_edge.product_uid
    ordered_vlan          = var.vlan
    vnic_index            = 0 # WAN vNIC
  }

  b_end = {
    requested_product_uid = data.megaport_partner.aws_dx.product_uid
  }

  b_end_partner_config = {
    partner = "aws"
    aws_config = {
      name          = var.vxc_name
      owner_account = var.aws_account_id
      amazon_asn    = 64512
      asn           = var.bgp_asn_customer
      auth_key      = var.bgp_auth_key != "" ? var.bgp_auth_key : null
      connect_type  = "AWSHC"
    }
  }
}

# --- VXC from Aviatrix Edge MGMT vNIC to Megaport Internet ---

resource "megaport_vxc" "mgmt_internet" {
  product_name         = "${var.vxc_name}-mgmt-internet"
  rate_limit           = var.vxc_bandwidth
  contract_term_months = var.port_term

  a_end = {
    requested_product_uid = megaport_mve.aviatrix_edge.product_uid
    vnic_index            = 2 # MGMT vNIC
  }

  b_end = {
    requested_product_uid = data.megaport_partner.internet.product_uid
  }

  b_end_partner_config = {
    partner = "transit"
  }
}

# --- Accept the Hosted Connection and create Private VIF ---
# AWSHC = Hosted Connection. Megaport provisions a hosted connection to our AWS account.
# We accept it, then create a private VIF on top associated to the DX gateway.

resource "aws_dx_private_virtual_interface" "this" {
  provider       = aws.us_east_1
  connection_id  = var.aws_dx_hosted_connection_id
  name           = var.vxc_name
  vlan           = var.vlan
  address_family = "ipv4"
  bgp_asn        = var.bgp_asn_customer
  dx_gateway_id  = var.aws_dx_gateway_id
}
